server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: users-service
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}
