server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: users-service
  config:
    #CONFIG FOR APP AND DATABASE
    location: appplication.yaml, liquibase.properties
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}