server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: users-service
  liquibase:
    change-log: classpath:db/changelog.xml
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:secret}
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/USERS_DB?createDatabaseIfNotExist=true}
  #    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}

jwt:
  config:
    expirationTime: 1200000
    secret: 3bJAp`]4|kzB?~8+